// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: resource/scheduler/scheduler.proto

package scheduler

import (
	resource "github.com/9triver/iarnet-global/internal/proto/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ComponentStatus Component 状态
type ComponentStatus int32

const (
	ComponentStatus_COMPONENT_STATUS_UNKNOWN   ComponentStatus = 0
	ComponentStatus_COMPONENT_STATUS_DEPLOYING ComponentStatus = 1
	ComponentStatus_COMPONENT_STATUS_RUNNING   ComponentStatus = 2
	ComponentStatus_COMPONENT_STATUS_STOPPED   ComponentStatus = 3
	ComponentStatus_COMPONENT_STATUS_ERROR     ComponentStatus = 4
)

// Enum value maps for ComponentStatus.
var (
	ComponentStatus_name = map[int32]string{
		0: "COMPONENT_STATUS_UNKNOWN",
		1: "COMPONENT_STATUS_DEPLOYING",
		2: "COMPONENT_STATUS_RUNNING",
		3: "COMPONENT_STATUS_STOPPED",
		4: "COMPONENT_STATUS_ERROR",
	}
	ComponentStatus_value = map[string]int32{
		"COMPONENT_STATUS_UNKNOWN":   0,
		"COMPONENT_STATUS_DEPLOYING": 1,
		"COMPONENT_STATUS_RUNNING":   2,
		"COMPONENT_STATUS_STOPPED":   3,
		"COMPONENT_STATUS_ERROR":     4,
	}
)

func (x ComponentStatus) Enum() *ComponentStatus {
	p := new(ComponentStatus)
	*p = x
	return p
}

func (x ComponentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComponentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_resource_scheduler_scheduler_proto_enumTypes[0].Descriptor()
}

func (ComponentStatus) Type() protoreflect.EnumType {
	return &file_resource_scheduler_scheduler_proto_enumTypes[0]
}

func (x ComponentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComponentStatus.Descriptor instead.
func (ComponentStatus) EnumDescriptor() ([]byte, []int) {
	return file_resource_scheduler_scheduler_proto_rawDescGZIP(), []int{0}
}

// DeployComponentRequest 部署 component 请求
type DeployComponentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 运行时环境（如 "python"）
	RuntimeEnv string `protobuf:"bytes,1,opt,name=runtime_env,json=runtimeEnv,proto3" json:"runtime_env,omitempty"`
	// 资源请求
	ResourceRequest *resource.Info `protobuf:"bytes,2,opt,name=resource_request,json=resourceRequest,proto3" json:"resource_request,omitempty"`
	// 目标节点 ID（可选，为空则在本地节点部署）
	// 如果指定，将在该节点上部署 component
	TargetNodeId string `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	// 目标节点地址（可选，如果指定了 target_node_id 但需要直接连接）
	TargetNodeAddress string `protobuf:"bytes,4,opt,name=target_node_address,json=targetNodeAddress,proto3" json:"target_node_address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeployComponentRequest) Reset() {
	*x = DeployComponentRequest{}
	mi := &file_resource_scheduler_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployComponentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployComponentRequest) ProtoMessage() {}

func (x *DeployComponentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_scheduler_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployComponentRequest.ProtoReflect.Descriptor instead.
func (*DeployComponentRequest) Descriptor() ([]byte, []int) {
	return file_resource_scheduler_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *DeployComponentRequest) GetRuntimeEnv() string {
	if x != nil {
		return x.RuntimeEnv
	}
	return ""
}

func (x *DeployComponentRequest) GetResourceRequest() *resource.Info {
	if x != nil {
		return x.ResourceRequest
	}
	return nil
}

func (x *DeployComponentRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *DeployComponentRequest) GetTargetNodeAddress() string {
	if x != nil {
		return x.TargetNodeAddress
	}
	return ""
}

// DeployComponentResponse 部署 component 响应
type DeployComponentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息（如果失败）
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Component 信息
	Component *ComponentInfo `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	// 部署的节点 ID
	NodeId string `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// 部署的节点名称
	NodeName string `protobuf:"bytes,5,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Provider ID（实际部署的 provider）
	ProviderId    string `protobuf:"bytes,6,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployComponentResponse) Reset() {
	*x = DeployComponentResponse{}
	mi := &file_resource_scheduler_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployComponentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployComponentResponse) ProtoMessage() {}

func (x *DeployComponentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_scheduler_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployComponentResponse.ProtoReflect.Descriptor instead.
func (*DeployComponentResponse) Descriptor() ([]byte, []int) {
	return file_resource_scheduler_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *DeployComponentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployComponentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeployComponentResponse) GetComponent() *ComponentInfo {
	if x != nil {
		return x.Component
	}
	return nil
}

func (x *DeployComponentResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DeployComponentResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *DeployComponentResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

// ComponentInfo Component 信息
type ComponentInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Component ID
	ComponentId string `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	// 镜像名称
	Image string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// 资源使用情况
	ResourceUsage *resource.Info `protobuf:"bytes,3,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	// Provider ID
	ProviderId    string `protobuf:"bytes,4,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentInfo) Reset() {
	*x = ComponentInfo{}
	mi := &file_resource_scheduler_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentInfo) ProtoMessage() {}

func (x *ComponentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_resource_scheduler_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentInfo.ProtoReflect.Descriptor instead.
func (*ComponentInfo) Descriptor() ([]byte, []int) {
	return file_resource_scheduler_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *ComponentInfo) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *ComponentInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ComponentInfo) GetResourceUsage() *resource.Info {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

func (x *ComponentInfo) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

// GetDeploymentStatusRequest 获取部署状态请求
type GetDeploymentStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Component ID
	ComponentId string `protobuf:"bytes,1,opt,name=component_id,json=componentId,proto3" json:"component_id,omitempty"`
	// 节点 ID（可选，如果指定则从该节点查询）
	NodeId        string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentStatusRequest) Reset() {
	*x = GetDeploymentStatusRequest{}
	mi := &file_resource_scheduler_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentStatusRequest) ProtoMessage() {}

func (x *GetDeploymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_scheduler_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeploymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_resource_scheduler_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeploymentStatusRequest) GetComponentId() string {
	if x != nil {
		return x.ComponentId
	}
	return ""
}

func (x *GetDeploymentStatusRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// GetDeploymentStatusResponse 获取部署状态响应
type GetDeploymentStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 错误信息（如果失败）
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Component 状态
	Status ComponentStatus `protobuf:"varint,3,opt,name=status,proto3,enum=scheduler.ComponentStatus" json:"status,omitempty"`
	// Component 信息
	Component     *ComponentInfo `protobuf:"bytes,4,opt,name=component,proto3" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeploymentStatusResponse) Reset() {
	*x = GetDeploymentStatusResponse{}
	mi := &file_resource_scheduler_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeploymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentStatusResponse) ProtoMessage() {}

func (x *GetDeploymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_scheduler_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDeploymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_resource_scheduler_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeploymentStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetDeploymentStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetDeploymentStatusResponse) GetStatus() ComponentStatus {
	if x != nil {
		return x.Status
	}
	return ComponentStatus_COMPONENT_STATUS_UNKNOWN
}

func (x *GetDeploymentStatusResponse) GetComponent() *ComponentInfo {
	if x != nil {
		return x.Component
	}
	return nil
}

var File_resource_scheduler_scheduler_proto protoreflect.FileDescriptor

const file_resource_scheduler_scheduler_proto_rawDesc = "" +
	"\n" +
	"\"resource/scheduler/scheduler.proto\x12\tscheduler\x1a\x17resource/resource.proto\"\xca\x01\n" +
	"\x16DeployComponentRequest\x12\x1f\n" +
	"\vruntime_env\x18\x01 \x01(\tR\n" +
	"runtimeEnv\x129\n" +
	"\x10resource_request\x18\x02 \x01(\v2\x0e.resource.InfoR\x0fresourceRequest\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeId\x12.\n" +
	"\x13target_node_address\x18\x04 \x01(\tR\x11targetNodeAddress\"\xd8\x01\n" +
	"\x17DeployComponentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x126\n" +
	"\tcomponent\x18\x03 \x01(\v2\x18.scheduler.ComponentInfoR\tcomponent\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x05 \x01(\tR\bnodeName\x12\x1f\n" +
	"\vprovider_id\x18\x06 \x01(\tR\n" +
	"providerId\"\xa0\x01\n" +
	"\rComponentInfo\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x125\n" +
	"\x0eresource_usage\x18\x03 \x01(\v2\x0e.resource.InfoR\rresourceUsage\x12\x1f\n" +
	"\vprovider_id\x18\x04 \x01(\tR\n" +
	"providerId\"X\n" +
	"\x1aGetDeploymentStatusRequest\x12!\n" +
	"\fcomponent_id\x18\x01 \x01(\tR\vcomponentId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"\xb9\x01\n" +
	"\x1bGetDeploymentStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x122\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1a.scheduler.ComponentStatusR\x06status\x126\n" +
	"\tcomponent\x18\x04 \x01(\v2\x18.scheduler.ComponentInfoR\tcomponent*\xa7\x01\n" +
	"\x0fComponentStatus\x12\x1c\n" +
	"\x18COMPONENT_STATUS_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aCOMPONENT_STATUS_DEPLOYING\x10\x01\x12\x1c\n" +
	"\x18COMPONENT_STATUS_RUNNING\x10\x02\x12\x1c\n" +
	"\x18COMPONENT_STATUS_STOPPED\x10\x03\x12\x1a\n" +
	"\x16COMPONENT_STATUS_ERROR\x10\x042\xd2\x01\n" +
	"\x10SchedulerService\x12X\n" +
	"\x0fDeployComponent\x12!.scheduler.DeployComponentRequest\x1a\".scheduler.DeployComponentResponse\x12d\n" +
	"\x13GetDeploymentStatus\x12%.scheduler.GetDeploymentStatusRequest\x1a&.scheduler.GetDeploymentStatusResponseB=Z;github.com/9triver/iarnet-global/internal/proto/schedulerb\x06proto3"

var (
	file_resource_scheduler_scheduler_proto_rawDescOnce sync.Once
	file_resource_scheduler_scheduler_proto_rawDescData []byte
)

func file_resource_scheduler_scheduler_proto_rawDescGZIP() []byte {
	file_resource_scheduler_scheduler_proto_rawDescOnce.Do(func() {
		file_resource_scheduler_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_scheduler_scheduler_proto_rawDesc), len(file_resource_scheduler_scheduler_proto_rawDesc)))
	})
	return file_resource_scheduler_scheduler_proto_rawDescData
}

var file_resource_scheduler_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resource_scheduler_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_resource_scheduler_scheduler_proto_goTypes = []any{
	(ComponentStatus)(0),                // 0: scheduler.ComponentStatus
	(*DeployComponentRequest)(nil),      // 1: scheduler.DeployComponentRequest
	(*DeployComponentResponse)(nil),     // 2: scheduler.DeployComponentResponse
	(*ComponentInfo)(nil),               // 3: scheduler.ComponentInfo
	(*GetDeploymentStatusRequest)(nil),  // 4: scheduler.GetDeploymentStatusRequest
	(*GetDeploymentStatusResponse)(nil), // 5: scheduler.GetDeploymentStatusResponse
	(*resource.Info)(nil),               // 6: resource.Info
}
var file_resource_scheduler_scheduler_proto_depIdxs = []int32{
	6, // 0: scheduler.DeployComponentRequest.resource_request:type_name -> resource.Info
	3, // 1: scheduler.DeployComponentResponse.component:type_name -> scheduler.ComponentInfo
	6, // 2: scheduler.ComponentInfo.resource_usage:type_name -> resource.Info
	0, // 3: scheduler.GetDeploymentStatusResponse.status:type_name -> scheduler.ComponentStatus
	3, // 4: scheduler.GetDeploymentStatusResponse.component:type_name -> scheduler.ComponentInfo
	1, // 5: scheduler.SchedulerService.DeployComponent:input_type -> scheduler.DeployComponentRequest
	4, // 6: scheduler.SchedulerService.GetDeploymentStatus:input_type -> scheduler.GetDeploymentStatusRequest
	2, // 7: scheduler.SchedulerService.DeployComponent:output_type -> scheduler.DeployComponentResponse
	5, // 8: scheduler.SchedulerService.GetDeploymentStatus:output_type -> scheduler.GetDeploymentStatusResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_resource_scheduler_scheduler_proto_init() }
func file_resource_scheduler_scheduler_proto_init() {
	if File_resource_scheduler_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_scheduler_scheduler_proto_rawDesc), len(file_resource_scheduler_scheduler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_scheduler_scheduler_proto_goTypes,
		DependencyIndexes: file_resource_scheduler_scheduler_proto_depIdxs,
		EnumInfos:         file_resource_scheduler_scheduler_proto_enumTypes,
		MessageInfos:      file_resource_scheduler_scheduler_proto_msgTypes,
	}.Build()
	File_resource_scheduler_scheduler_proto = out.File
	file_resource_scheduler_scheduler_proto_goTypes = nil
	file_resource_scheduler_scheduler_proto_depIdxs = nil
}
