// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: resource.proto

package resource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           int64                  `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int64                  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"`
	Gpu           int64                  `protobuf:"varint,3,opt,name=gpu,proto3" json:"gpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Info) GetCpu() int64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Info) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *Info) GetGpu() int64 {
	if x != nil {
		return x.Gpu
	}
	return 0
}

type Capacity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         *Info                  `protobuf:"bytes,1,opt,name=total,proto3" json:"total,omitempty"`
	Used          *Info                  `protobuf:"bytes,2,opt,name=used,proto3" json:"used,omitempty"`
	Available     *Info                  `protobuf:"bytes,3,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capacity) Reset() {
	*x = Capacity{}
	mi := &file_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capacity) ProtoMessage() {}

func (x *Capacity) ProtoReflect() protoreflect.Message {
	mi := &file_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capacity.ProtoReflect.Descriptor instead.
func (*Capacity) Descriptor() ([]byte, []int) {
	return file_resource_proto_rawDescGZIP(), []int{1}
}

func (x *Capacity) GetTotal() *Info {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *Capacity) GetUsed() *Info {
	if x != nil {
		return x.Used
	}
	return nil
}

func (x *Capacity) GetAvailable() *Info {
	if x != nil {
		return x.Available
	}
	return nil
}

var File_resource_proto protoreflect.FileDescriptor

const file_resource_proto_rawDesc = "" +
	"\n" +
	"\x0eresource.proto\x12\bresource\"B\n" +
	"\x04Info\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x03R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x03R\x06memory\x12\x10\n" +
	"\x03gpu\x18\x03 \x01(\x03R\x03gpu\"\x82\x01\n" +
	"\bCapacity\x12$\n" +
	"\x05total\x18\x01 \x01(\v2\x0e.resource.InfoR\x05total\x12\"\n" +
	"\x04used\x18\x02 \x01(\v2\x0e.resource.InfoR\x04used\x12,\n" +
	"\tavailable\x18\x03 \x01(\v2\x0e.resource.InfoR\tavailableB:Z8github.com/9triver/iarnet-global/internal/proto/resourceb\x06proto3"

var (
	file_resource_proto_rawDescOnce sync.Once
	file_resource_proto_rawDescData []byte
)

func file_resource_proto_rawDescGZIP() []byte {
	file_resource_proto_rawDescOnce.Do(func() {
		file_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resource_proto_rawDesc), len(file_resource_proto_rawDesc)))
	})
	return file_resource_proto_rawDescData
}

var file_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_proto_goTypes = []any{
	(*Info)(nil),     // 0: resource.Info
	(*Capacity)(nil), // 1: resource.Capacity
}
var file_resource_proto_depIdxs = []int32{
	0, // 0: resource.Capacity.total:type_name -> resource.Info
	0, // 1: resource.Capacity.used:type_name -> resource.Info
	0, // 2: resource.Capacity.available:type_name -> resource.Info
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_resource_proto_init() }
func file_resource_proto_init() {
	if File_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resource_proto_rawDesc), len(file_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_resource_proto_goTypes,
		DependencyIndexes: file_resource_proto_depIdxs,
		MessageInfos:      file_resource_proto_msgTypes,
	}.Build()
	File_resource_proto = out.File
	file_resource_proto_goTypes = nil
	file_resource_proto_depIdxs = nil
}
